### ISSUE TITLE
Dimensions of captured Bitmap are limited to a device screen size 

### ISSUE THREAD

**Issue by davidbilik** [sergio-sastre/AndroidUiTestingUtils#54]
Hello, I am using this test to screenshot test some composables

```
abstract class ScreenshotTest {

    @get:Rule
    val rule = ActivityScenarioForComposableRule(
        config = ComposableConfigItem(
            displaySize = NORMAL,
            orientation = PORTRAIT,
        )
    )

    protected fun snapshotComposable(
        name: String,
        composable: @Composable () -> Unit
    ) {
        rule.activityScenario
            .onActivity { activity ->
                activity.setContent {
                    composable()
               }
            }
        rule.activity
            .waitForComposeView()
            .captureToBitmap()
            .get()
            .writeToTestStorage(name)
    }
}
```

and I've noticed that if the rendered view is higher than the screen height it's cut. Is there any way to get a bitmap of the whole view regardless of the device size? I've tried to play with `displaySize` property of a `ComposableConfigItem` but it's only scaling the image not solving the issue. Is it even something your library can affect?

Thanks for the input :)

**Comment by davidbilik** [comment]
Ok so I rewrote my test like this, without using your library, 

```
abstract class ScreenshotTest {

    @get:Rule
    val rule = createComposeRule()

    protected fun snapshotComposable(
        name: String,
        composable: @Composable () -> Unit
    ) {
        rule.setContent {
                composable()
        }
        rule.onAllNodes(isRoot())
            .onFirst()
            .captureToImage()
            .asAndroidBitmap()
            .writeToTestStorage(name)
    }
}
```

and it's still the same :(

**Comment by sergio-sastre** [comment]
Hi @davidbilik !
I'm afraid that is because you are using `captureToBitmap()` or `captureToImage()`
Those methods limit the bitmap to the window size i.e what is visible on the screen.

However, this library provides `view.drawToBitmap()`, which uses Canvas, which should allow you to take screenshots that outsize the screen window.

e.g.
```kotlin
abstract class ScreenshotTest {

    @get:Rule
    val rule = ActivityScenarioForComposableRule(
        config = ComposableConfigItem(
            orientation = PORTRAIT,
        )
    )

    protected fun snapshotComposable(
        name: String,
        composable: @Composable () -> Unit
    ) {
        rule.activityScenario
            .onActivity { activity ->
                activity.setContent {
                    composable()
               }
            }
        rule.activity
            .waitForComposeView()
            .drawToBitmap() // this is the key
            .writeToTestStorage(name)
    }
}
```
The only disadvantage of that method, is that elevation elements (like shadows) are not drawn.

Alternatively, you could use 
```kotlin
@get:Rule
    val rule = ActivityScenarioForComposableRule(
       // make the composable smaller, 
       // to see whether it fits in the window, 
       // without sacrificing elevation
        config = ComposableConfigItem(
             displaySize = SMALL, 
        )
    )  
 ```

Warning: the library also provides `view.drawToBitmapWithElevation()`, but that uses PixelCopy, which limits the screenshot to the window size :(

let me know if that helped :)

**Comment by davidbilik** [comment]
Hey Sergio, thanks for you answer :) I've tried to rewrite my test to this

```kotlin
protected fun snapshotComposable(
        name: String,
        composable: @Composable () -> Unit
    ) {
        rule.activityScenario
            .onActivity { activity ->
                activity.setContent {
                      composable()
                }
            }
        rule.activity
            .waitForComposeView()
            .drawToBitmap()
            .writeToTestStorage(name)
    }
```

and it's still limited to a screen size 🤔 But maybe i did something wrong because you've said

>  However, this library provides view.drawToBitmap(), which uses Canvas

and I did not find this method in your library, I've used the one from core-ktx.

**Comment by sergio-sastre** [comment]
@davidbilik 
Although it seems it is not related to this lib, could you share the problematic composable?

I could take a look at it and might find a solution to the problem

**Comment by sergio-sastre** [comment]
@davidbilik 
I'll close this issue seems it does not seem to be related to this lib
