### ISSUE TITLE
1.2.4 no longer on jitpack

### ISSUE THREAD

**Issue by yannickpulver** [sergio-sastre/AndroidUiTestingUtils#59]
**Describe the bug**
It seems that 1.2.4 is no longer accessible on jitpack. 

For example, 1.2.3 is still working fine:
https://jitpack.io/com/github/sergio-sastre/AndroidUiTestingUtils/1.2.3/build.log

But 1.2.4 is currently missing
https://jitpack.io/com/github/sergio-sastre/AndroidUiTestingUtils/1.2.4/build.log

**Additional context**
This might be an issue from jitpack itself, but just wanted to report it here aswell. Maybe a retrigger/retagging of this version could help to trigger jitpacks pipeline again?

**Comment by sergio-sastre** [comment]
Hi @yannickpulver !
It looks like it is working again.

Btw, 2.0.0-beta01 is the same as 1.2.4 but with extra modules, and no breaking changes.

So it could also be downloaded using:
androidTestImplementation 'com.github.sergio-sastre.AndroidUiTestingUtils:utils:2.0.0-beta01', for the same functionality as 1.2.4

I've also considered to migrate to maven central for better stability... but it probably won't happen before 2.0.0 is final.

Let me know if you still have problems, I can always provide you with the .jar

**Comment by sergio-sastre** [comment]
Jitpack is up again

**Comment by yannickpulver** [comment]
Thanks! Great library by the way 🙌
